In [57]:
import os
import pandas as pd
import numpy as np
import sys

In [58]:
xlfilename = "TSS_TN_744090_29042022 - Copy.xlsm"
bookname = "THE LAST FIGHTING TOMMY"

In [59]:
dfbd = pd.read_excel(xlfilename, nrows=1,usecols="A:B", sheet_name="INDEX")
dfbd

     Vendor Code File Location
0  TSS_TN_744090         E:\B1

In [60]:
vendorcode = dfbd['Vendor Code'][0]
filelocation = dfbd['File Location'][0]

In [61]:
dfxl = pd.read_excel(xlfilename, skiprows=4, sheet_name="INDEX" )
dfxl

,CONTENTS,HELEN BATTEN SISTERS OF THE EAST END,KATE HARRISON THE SECRET SHOPPER UNWRAPPED,DANIELLE STEEL AGAINST ALL ODDS,MICHAEL MORPURGO AN EAGLE IN THE SNOW,CATHY KELLY ONCE IN A LIFETIME,KITTY NEALE A FAMILY'S HEART BREAK,WELCOME TO THE REAL WORLD CAROLE MATTHEWS,CELEBRITEENS IN THE SPOTLIGHT JOANNA PHILBIN,THE BEACH HOUSE JANE GREEN,...,BLOOD SAFARI DEON MEYER,KISS THE GIRLS JAMES PATTERSON,RUNNING AWAY FROM RICHARD CHRIS MANBY,VIOLETS ARE BLUE JAMES PATTERSON,BILLY GRAHAM UNTO THE HILLS,ELVI RHODES PORTRAIT OF CHLOE,WARCRAFT WAR OF THE ANCIENTS THE DEMON SOUL,MELISSA NATHAN THE WAITRESS,"PROMISES, PROMISES ERICA JAMES",GERALD SEYMOUR TRAITOR'S KISS
0,Notes,0,0,0,0,0,0,1. Running Chapters,0,0,...,0,1. Chapter 25 in page no. 96 is wrongly printe...,0,0,1. No chapters available,0,"1. Total Pages wrongly mentioned as 386, corre...",0,0,0
1,Bar Code,9780091951771,9781409103530,9781509800223,9780008134174,9780007240432,9780008270919,9780751551426,9781407131801,9780141022031,...,9781444739206,9780006493150,9780340835845,9780747266914,9780850091168,9780552145770,76714006997,9780099427988,9781407245812,9780552150439
2,No of Pages,320,396,432,272,478,432,416,288,448,...,384,480,448,480,368,512,384,528,448,544
3,No of Front Cover,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,No of Back Cover,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,CHAPTER 396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
403,CHAPTER 397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
404,CHAPTER 398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405,CHAPTER 399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
406,CHAPTER 400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df=dfxl[['CONTENTS', bookname]].copy()
df

              CONTENTS                            THE LAST FIGHTING TOMMY
0                Notes  1. Between Page No 112 & 133, 16 un-numbered p...
1             Bar Code                                      9780747593362
2          No of Pages                                                256
3    No of Front Cover                                                  1
4     No of Back Cover                                                  1
..                 ...                                                ...
402        CHAPTER 396                                                NaN
403        CHAPTER 397                                                NaN
404        CHAPTER 398                                                NaN
405        CHAPTER 399                                                NaN
406        CHAPTER 400                                                NaN

[407 rows x 2 columns]

In [63]:
df = df.drop(index = [0]).copy()
df = df.reset_index(drop=True)

In [64]:
df.dropna(subset=[bookname], inplace=True)
df

             CONTENTS THE LAST FIGHTING TOMMY
0            Bar Code           9780747593362
1         No of Pages                     256
2   No of Front Cover                       1
3    No of Back Cover                       1
4        INTRODUCTION                    1-30
5                 END                 208-240
6           CHAPTER 1                      15
7           CHAPTER 2                      41
8           CHAPTER 3                      55
9           CHAPTER 4                      68
10          CHAPTER 5                      85
11          CHAPTER 6             108-126, 16
12          CHAPTER 7                     127
13          CHAPTER 8                     137
14          CHAPTER 9                     162
15         CHAPTER 10                     188
16         CHAPTER 11                 199-207

In [65]:
duplicate  = df[df.duplicated('CONTENTS')].copy()

print("Duplicate Rows :")

duplicate

Duplicate Rows :

Empty DataFrame
Columns: [CONTENTS, THE LAST FIGHTING TOMMY]
Index: []

In [66]:
for i in duplicate['CONTENTS']:
    print(i)
    l = len(df['CONTENTS'])
    k = 1
    for j in range(l):
        if df['CONTENTS'][j] == i:
            df['CONTENTS'][j] = df['CONTENTS'][j] + " " + str(k)
            k = k + 1

df

             CONTENTS THE LAST FIGHTING TOMMY
0            Bar Code           9780747593362
1         No of Pages                     256
2   No of Front Cover                       1
3    No of Back Cover                       1
4        INTRODUCTION                    1-30
5                 END                 208-240
6           CHAPTER 1                      15
7           CHAPTER 2                      41
8           CHAPTER 3                      55
9           CHAPTER 4                      68
10          CHAPTER 5                      85
11          CHAPTER 6             108-126, 16
12          CHAPTER 7                     127
13          CHAPTER 8                     137
14          CHAPTER 9                     162
15         CHAPTER 10                     188
16         CHAPTER 11                 199-207

In [67]:
df_bk = df.drop(index = [0,1]).copy()
df_bk = df_bk.reset_index(drop=True)
df_bk

             CONTENTS THE LAST FIGHTING TOMMY
0   No of Front Cover                       1
1    No of Back Cover                       1
2        INTRODUCTION                    1-30
3                 END                 208-240
4           CHAPTER 1                      15
5           CHAPTER 2                      41
6           CHAPTER 3                      55
7           CHAPTER 4                      68
8           CHAPTER 5                      85
9           CHAPTER 6             108-126, 16
10          CHAPTER 7                     127
11          CHAPTER 8                     137
12          CHAPTER 9                     162
13         CHAPTER 10                     188
14         CHAPTER 11                 199-207

In [68]:
# ADD: FRONT OUTER & FRONT INNER
if df_bk[bookname][0] == 1:
    y = "COVER_FRONT OUTER"
    z = "COVER_FRONT INNER"
    line1 = pd.DataFrame({"CONTENTS":[z],bookname: [0]}, index=[2.5])
    line2 = pd.DataFrame({"CONTENTS":[y],bookname: [0]}, index=[2.6])
    df_bk = pd.concat([df_bk.iloc[:2],line1,df_bk.iloc[2:]]).reset_index(drop=True)
    df_bk = pd.concat([df_bk.iloc[:2],line2,df_bk.iloc[2:]]).reset_index(drop=True)                

    
if df_bk[bookname][0] > 1:
    x = df_bk[bookname][0]
    print(x)
    for i in reversed(range(x)):
        print(i)
        y = "COVER_FRONT OUTER "+ str(i+1)
        z = "COVER_FRONT INNER "+ str(i+1)
        line1 = pd.DataFrame({"CONTENTS":[z],bookname: [0]}, index=[i+2.5])
        line2 = pd.DataFrame({"CONTENTS":[y],bookname: [0]}, index=[i+2.6])
        df_bk = pd.concat([df_bk.iloc[:2],line1,df_bk.iloc[2:]]).reset_index(drop=True)
        df_bk = pd.concat([df_bk.iloc[:2],line2,df_bk.iloc[2:]]).reset_index(drop=True)                

df_bk

             CONTENTS THE LAST FIGHTING TOMMY
0   No of Front Cover                       1
1    No of Back Cover                       1
2   COVER_FRONT OUTER                       0
3   COVER_FRONT INNER                       0
4        INTRODUCTION                    1-30
5                 END                 208-240
6           CHAPTER 1                      15
7           CHAPTER 2                      41
8           CHAPTER 3                      55
9           CHAPTER 4                      68
10          CHAPTER 5                      85
11          CHAPTER 6             108-126, 16
12          CHAPTER 7                     127
13          CHAPTER 8                     137
14          CHAPTER 9                     162
15         CHAPTER 10                     188
16         CHAPTER 11                 199-207

In [69]:
# move END 
y = df_bk.index[df_bk['CONTENTS'].str.contains('END')].tolist()
print (y)
idx = df_bk.index.tolist()
idx = idx + y
for i in reversed(y):
    idx.pop(i)
    print(idx)
df_bk = df_bk.reindex(idx)
df_bk = df_bk.reset_index(drop=True)
df_bk

[5]
[0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 5]

             CONTENTS THE LAST FIGHTING TOMMY
0   No of Front Cover                       1
1    No of Back Cover                       1
2   COVER_FRONT OUTER                       0
3   COVER_FRONT INNER                       0
4        INTRODUCTION                    1-30
5           CHAPTER 1                      15
6           CHAPTER 2                      41
7           CHAPTER 3                      55
8           CHAPTER 4                      68
9           CHAPTER 5                      85
10          CHAPTER 6             108-126, 16
11          CHAPTER 7                     127
12          CHAPTER 8                     137
13          CHAPTER 9                     162
14         CHAPTER 10                     188
15         CHAPTER 11                 199-207
16                END                 208-240

In [70]:
# ADD: BACK INNER & BACK OUTER

if df_bk[bookname][1] == 1:
    y = "COVER_BACK INNER"
    z = "COVER_BACK OUTER"
    line1 = pd.DataFrame({"CONTENTS":[y],bookname: [0]})
    line2 = pd.DataFrame({"CONTENTS":[z],bookname: [0]})
    df_bk = pd.concat([df_bk,line1]).reset_index(drop=True)
    df_bk = pd.concat([df_bk,line2]).reset_index(drop=True)                

    
if df_bk[bookname][1] > 1:
    x = df_bk[bookname][0]
    print(x)
    for i in range(x):
        print(i)
        y = "COVER_BACK INNER "+ str(i+1)
        z = "COVER_BACK OUTER "+ str(i+1)
        line1 = pd.DataFrame({"CONTENTS":[y],bookname: [0]})
        line2 = pd.DataFrame({"CONTENTS":[z],bookname: [0]})
        df_bk = pd.concat([df_bk,line1]).reset_index(drop=True)
        df_bk = pd.concat([df_bk,line2]).reset_index(drop=True)                


df_bk

             CONTENTS THE LAST FIGHTING TOMMY
0   No of Front Cover                       1
1    No of Back Cover                       1
2   COVER_FRONT OUTER                       0
3   COVER_FRONT INNER                       0
4        INTRODUCTION                    1-30
5           CHAPTER 1                      15
6           CHAPTER 2                      41
7           CHAPTER 3                      55
8           CHAPTER 4                      68
9           CHAPTER 5                      85
10          CHAPTER 6             108-126, 16
11          CHAPTER 7                     127
12          CHAPTER 8                     137
13          CHAPTER 9                     162
14         CHAPTER 10                     188
15         CHAPTER 11                 199-207
16                END                 208-240
17   COVER_BACK INNER                       0
18   COVER_BACK OUTER                       0

In [71]:
# Add 'Page From' column
import re
PageFrom = df_bk[bookname].copy()
for i in range(2,len(PageFrom)):
    if type(PageFrom[i]) != int:
        x = PageFrom[i]
        y = re.split(',|-',x)
        z = y[0]
        PageFrom[i]=z

df_bk['Page From'] = PageFrom
df_bk["Page From"] = pd.to_numeric(df_bk["Page From"])
df_bk

             CONTENTS THE LAST FIGHTING TOMMY  Page From
0   No of Front Cover                       1          1
1    No of Back Cover                       1          1
2   COVER_FRONT OUTER                       0          0
3   COVER_FRONT INNER                       0          0
4        INTRODUCTION                    1-30          1
5           CHAPTER 1                      15         15
6           CHAPTER 2                      41         41
7           CHAPTER 3                      55         55
8           CHAPTER 4                      68         68
9           CHAPTER 5                      85         85
10          CHAPTER 6             108-126, 16        108
11          CHAPTER 7                     127        127
12          CHAPTER 8                     137        137
13          CHAPTER 9                     162        162
14         CHAPTER 10                     188        188
15         CHAPTER 11                 199-207        199
16                END                 208-240        208
17   COVER_BACK INNER                       0          0
18   COVER_BACK OUTER                       0          0

In [72]:
# Add 'Page To' column
import re
PageTo = df_bk[bookname].copy()
for i in range(2,len(PageTo)):
    if PageTo[i] != 0:
        if type(PageTo[i]) == int:
            if int(PageFrom[i+1]) > PageTo[i]:
                    PageTo[i] = int(PageFrom[i+1])-1
        if type(PageTo[i]) != int:
            x = PageTo[i]
            y = x.split("-")
            z = y[-1]
            q = z.split(",")
            p = q[0]
            print(p)
            PageTo[i]=p

    else:
        PageTo[i] = 0

df_bk['Page To'] = PageTo
df_bk["Page To"] = pd.to_numeric(df_bk["Page To"])
df_bk

30
126
207
240

             CONTENTS THE LAST FIGHTING TOMMY  Page From  Page To
0   No of Front Cover                       1          1        1
1    No of Back Cover                       1          1        1
2   COVER_FRONT OUTER                       0          0        0
3   COVER_FRONT INNER                       0          0        0
4        INTRODUCTION                    1-30          1       30
5           CHAPTER 1                      15         15       40
6           CHAPTER 2                      41         41       54
7           CHAPTER 3                      55         55       67
8           CHAPTER 4                      68         68       84
9           CHAPTER 5                      85         85      107
10          CHAPTER 6             108-126, 16        108      126
11          CHAPTER 7                     127        127      136
12          CHAPTER 8                     137        137      161
13          CHAPTER 9                     162        162      187
14         CHAPTER 10                     188        188      198
15         CHAPTER 11                 199-207        199      207
16                END                 208-240        208      240
17   COVER_BACK INNER                       0          0        0
18   COVER_BACK OUTER                       0          0        0

In [73]:
# Add NonNumbered Pages
NonNumberedPages = df_bk[bookname].copy()
for i in range(len(NonNumberedPages)):
    if ',' in str(NonNumberedPages[i]):
        x = NonNumberedPages[i]
        y = x.split(",")
        z = y[-1]
        print(z)
        NonNumberedPages[i]=z

    else:
        NonNumberedPages[i] = 0

df_bk['NonNumberedPages'] = NonNumberedPages
df_bk["NonNumberedPages"] = pd.to_numeric(df_bk["NonNumberedPages"])
df_bk

 16

,CONTENTS,THE LAST FIGHTING TOMMY,Page From,Page To,NonNumberedPages
0,No of Front Cover,1,1,1,0
1,No of Back Cover,1,1,1,0
2,COVER_FRONT OUTER,0,0,0,0
3,COVER_FRONT INNER,0,0,0,0
4,INTRODUCTION,1-30,1,30,0
5,CHAPTER 1,15,15,40,0
6,CHAPTER 2,41,41,54,0
7,CHAPTER 3,55,55,67,0
8,CHAPTER 4,68,68,84,0
9,CHAPTER 5,85,85,107,0
10,CHAPTER 6,"108-126, 16",108,126,16
11,CHAPTER 7,127,127,136,0
12,CHAPTER 8,137,137,161,0
13,CHAPTER 9,162,162,187,0
14,CHAPTER 10,188,188,198,0
15,CHAPTER 11,199-207,199,207,0
16,END,208-240,208,240,0
17,COVER_BACK INNER,0,0,0,0
18,COVER_BACK OUTER,0,0,0,0

In [74]:
# Add No of Pages
NoofPages=[0,0]
for i in range(2,len(PageTo)):
    j = int(df_bk['Page To'][i]) - int(df_bk['Page From'][i]) + 1+int(df_bk['NonNumberedPages'][i])
    NoofPages.append(j)
    
df_bk['No of Pages'] = NoofPages
df_bk["No of Pages"] = pd.to_numeric(df_bk["No of Pages"])
df_bk

,CONTENTS,THE LAST FIGHTING TOMMY,Page From,Page To,NonNumberedPages,No of Pages
0,No of Front Cover,1,1,1,0,0
1,No of Back Cover,1,1,1,0,0
2,COVER_FRONT OUTER,0,0,0,0,1
3,COVER_FRONT INNER,0,0,0,0,1
4,INTRODUCTION,1-30,1,30,0,30
5,CHAPTER 1,15,15,40,0,26
6,CHAPTER 2,41,41,54,0,14
7,CHAPTER 3,55,55,67,0,13
8,CHAPTER 4,68,68,84,0,17
9,CHAPTER 5,85,85,107,0,23
10,CHAPTER 6,"108-126, 16",108,126,16,35
11,CHAPTER 7,127,127,136,0,10
12,CHAPTER 8,137,137,161,0,25
13,CHAPTER 9,162,162,187,0,26
14,CHAPTER 10,188,188,198,0,11
15,CHAPTER 11,199-207,199,207,0,9
16,END,208-240,208,240,0,33
17,COVER_BACK INNER,0,0,0,0,1
18,COVER_BACK OUTER,0,0,0,0,1

In [75]:
# drop no of Front Cover & no of Back Cover
df_bk = df_bk.drop([0,1]).reset_index(drop=True)
df_bk

,CONTENTS,THE LAST FIGHTING TOMMY,Page From,Page To,NonNumberedPages,No of Pages
0,COVER_FRONT OUTER,0,0,0,0,1
1,COVER_FRONT INNER,0,0,0,0,1
2,INTRODUCTION,1-30,1,30,0,30
3,CHAPTER 1,15,15,40,0,26
4,CHAPTER 2,41,41,54,0,14
5,CHAPTER 3,55,55,67,0,13
6,CHAPTER 4,68,68,84,0,17
7,CHAPTER 5,85,85,107,0,23
8,CHAPTER 6,"108-126, 16",108,126,16,35
9,CHAPTER 7,127,127,136,0,10
10,CHAPTER 8,137,137,161,0,25
11,CHAPTER 9,162,162,187,0,26
12,CHAPTER 10,188,188,198,0,11
13,CHAPTER 11,199-207,199,207,0,9
14,END,208-240,208,240,0,33
15,COVER_BACK INNER,0,0,0,0,1
16,COVER_BACK OUTER,0,0,0,0,1

In [76]:
# split chapters

df_bk1 = df_bk.copy()
df_bk1

,CONTENTS,THE LAST FIGHTING TOMMY,Page From,Page To,NonNumberedPages,No of Pages
0,COVER_FRONT OUTER,0,0,0,0,1
1,COVER_FRONT INNER,0,0,0,0,1
2,INTRODUCTION,1-30,1,30,0,30
3,CHAPTER 1,15,15,40,0,26
4,CHAPTER 2,41,41,54,0,14
5,CHAPTER 3,55,55,67,0,13
6,CHAPTER 4,68,68,84,0,17
7,CHAPTER 5,85,85,107,0,23
8,CHAPTER 6,"108-126, 16",108,126,16,35
9,CHAPTER 7,127,127,136,0,10
10,CHAPTER 8,137,137,161,0,25
11,CHAPTER 9,162,162,187,0,26
12,CHAPTER 10,188,188,198,0,11
13,CHAPTER 11,199-207,199,207,0,9
14,END,208-240,208,240,0,33
15,COVER_BACK INNER,0,0,0,0,1
16,COVER_BACK OUTER,0,0,0,0,1

In [77]:
dr=[]
for i in range(len(df_bk1['CONTENTS'])):
    print(df_bk1['CONTENTS'][i])
    if "FRONT" in df_bk['CONTENTS'][i]:
        dr.append(i)
    if "BACK" in df_bk['CONTENTS'][i]:
        dr.append(i)
df_bk1 = df_bk1.drop(index = dr).copy()
df_bk1

COVER_FRONT OUTER
COVER_FRONT INNER
INTRODUCTION
CHAPTER 1
CHAPTER 2
CHAPTER 3
CHAPTER 4
CHAPTER 5
CHAPTER 6
CHAPTER 7
CHAPTER 8
CHAPTER 9
CHAPTER 10
CHAPTER 11
END
COVER_BACK INNER
COVER_BACK OUTER

,CONTENTS,THE LAST FIGHTING TOMMY,Page From,Page To,NonNumberedPages,No of Pages
2,INTRODUCTION,1-30,1,30,0,30
3,CHAPTER 1,15,15,40,0,26
4,CHAPTER 2,41,41,54,0,14
5,CHAPTER 3,55,55,67,0,13
6,CHAPTER 4,68,68,84,0,17
7,CHAPTER 5,85,85,107,0,23
8,CHAPTER 6,"108-126, 16",108,126,16,35
9,CHAPTER 7,127,127,136,0,10
10,CHAPTER 8,137,137,161,0,25
11,CHAPTER 9,162,162,187,0,26
12,CHAPTER 10,188,188,198,0,11
13,CHAPTER 11,199-207,199,207,0,9
14,END,208-240,208,240,0,33

In [78]:
# split pdf chapterwise

# add front cover
j =df[bookname][2] # no of front cover
for p in reversed(range(int(j))):
    if j == 1:
        q = str(1)
        r = str(2)
        dffc = {'CONTENTS': 'FRONT COVER',
                bookname: q+"-"+r,
                'Page From': q,
                'Page To': r,
                'No of Pages': str(int(r)-int(q)+1)}
        dffc = pd.DataFrame(dffc, index=[0])
        df_bk1 = dffc.append(df_bk1)
        df_bk1 = df_bk1.reset_index(drop = True)

    if j > 1: 
        q = str(p+p+1)
        r = str((p+1)*2)
        dffc = {'CONTENTS': "FRONT COVER "+str(p+1),
               bookname: q+"-"+r,
               'Page From': q,
               'Page To': r,
               'No of Pages': str(int(r)-int(q)+1)}
        dffc = pd.DataFrame(dffc, index=[0])
        df_bk1 = dffc.append(df_bk1)
        df_bk1 = df_bk1.reset_index(drop = True)
        
        
# add back cover
k =df[bookname][3]
for p in reversed(range(int(k))):
    if k == 1:
        q = str(1)
        r = str(2)
        dfbc = {'CONTENTS': "BACK COVER",
               bookname: q+"-"+r,
               'Page From': q,
               'Page To': r,
               'No of Pages': str(int(r)-int(q)+1)}
        dfbc = pd.DataFrame(dfbc, index=[0])
        df_bk1 = df_bk1.append(dfbc)
        df_bk1 = df_bk1.reset_index(drop = True)


    if k > 1:
        q = str(p+p+1)
        r = str((p+1)*2)
        dfbc = {'CONTENTS': "BACK COVER "+str(p+1),
               bookname: q+"-"+r,
               'Page From': q,
               'Page To': r,
               'No of Pages': str(int(r)-int(q)+1)}
        dfbc = pd.DataFrame(dfbc, index=[0])
        df_bk1 = df_bk1.append(dfbc)
        df_bk1 = df_bk1.reset_index(drop = True)

df_bk1

,CONTENTS,THE LAST FIGHTING TOMMY,Page From,Page To,No of Pages,NonNumberedPages
0,FRONT COVER,1-2,1,2,2,NaN
1,INTRODUCTION,1-30,1,30,30,0.0
2,CHAPTER 1,15,15,40,26,0.0
3,CHAPTER 2,41,41,54,14,0.0
4,CHAPTER 3,55,55,67,13,0.0
5,CHAPTER 4,68,68,84,17,0.0
6,CHAPTER 5,85,85,107,23,0.0
7,CHAPTER 6,"108-126, 16",108,126,35,16.0
8,CHAPTER 7,127,127,136,10,0.0
9,CHAPTER 8,137,137,161,25,0.0
10,CHAPTER 9,162,162,187,26,0.0
11,CHAPTER 10,188,188,198,11,0.0
12,CHAPTER 11,199-207,199,207,9,0.0
13,END,208-240,208,240,33,0.0
14,BACK COVER,1-2,1,2,2,NaN

In [79]:
# Add Total Pages, Split From & Split To
NoP=df_bk1['No of Pages']
NoP
TOTALPAGES = [NoP[0]]
j = int(NoP[0])
for i in range(1,len(NoP)):
    if df_bk1['Page From'][i] == df_bk1['Page To'][i-1]:
        j = j + int(NoP[i])-1
        TOTALPAGES.append(j)
    else:
        j = j + int(NoP[i])
        TOTALPAGES.append(j)
    
#for i in range(len(NoP)):
#    j = j + int(NoP[i])
#    TOTALPAGES.append(j)
    

print(TOTALPAGES)
df_bk1['Total Pages'] = TOTALPAGES


splitfrom=[int(df_bk1['Page From'][0])]
splitto=[int(df_bk1['Page To'][0])]

for i in range(1,len(df_bk1['CONTENTS'])):
    if df_bk1['Page From'][i] == df_bk1['Page To'][i-1]:
        p = df_bk1['Total Pages'][i-1]
    else:
        p = int(df_bk1['Total Pages'][i-1])+1
    splitfrom.append(p)
    q = p + int(df_bk1['No of Pages'][i]) - 1
    splitto.append(q)

df_bk1['Split From']=splitfrom
df_bk1['Split To']=splitto

df_bk1

['2', 32, 58, 72, 85, 102, 125, 160, 170, 195, 221, 232, 241, 274, 276]

,CONTENTS,THE LAST FIGHTING TOMMY,Page From,Page To,No of Pages,NonNumberedPages,Total Pages,Split From,Split To
0,FRONT COVER,1-2,1,2,2,NaN,2,1,2
1,INTRODUCTION,1-30,1,30,30,0.0,32,3,32
2,CHAPTER 1,15,15,40,26,0.0,58,33,58
3,CHAPTER 2,41,41,54,14,0.0,72,59,72
4,CHAPTER 3,55,55,67,13,0.0,85,73,85
5,CHAPTER 4,68,68,84,17,0.0,102,86,102
6,CHAPTER 5,85,85,107,23,0.0,125,103,125
7,CHAPTER 6,"108-126, 16",108,126,35,16.0,160,126,160
8,CHAPTER 7,127,127,136,10,0.0,170,161,170
9,CHAPTER 8,137,137,161,25,0.0,195,171,195
10,CHAPTER 9,162,162,187,26,0.0,221,196,221
11,CHAPTER 10,188,188,198,11,0.0,232,222,232
12,CHAPTER 11,199-207,199,207,9,0.0,241,233,241
13,END,208-240,208,240,33,0.0,274,242,274
14,BACK COVER,1-2,1,2,2,NaN,276,275,276

In [80]:
#import sys
#from pdfminer.pdfparser import PDFParser
#from pdfminer.pdfdocument import PDFDocument
#from pdfminer.pdfpage import PDFPage
#from pdfminer.pdfinterp import resolve1

#path = filelocation+"\\SCAN\\\WHOLEBOOK1\\"
#dir_list = os.listdir(path)
#i = 0

#if len(os.listdir(filelocation+"\SCAN\\WHOLEBOOK1") ) == 1:
#    for x in dir_list:
#        file = open(path+x, 'rb')
#        parser = PDFParser(file)
#        document = PDFDocument(parser)

#i = i + resolve1(document.catalog['Pages'])['Count']
#print(x+":"+str(i))
#file.close()

In [81]:
import shutil

# DELETE SCAN FOLDERS
path = filelocation+"\\SCAN"
if os.path.exists(path+"\\CHAPTERS"):
    if len(os.listdir(path+"\\CHAPTERS") ) == 0:
        shutil.rmtree(path+"\\CHAPTERS")
if os.path.exists(path+"\\PAGES"):
    if len(os.listdir(path+"\\PAGES") ) == 0:
        shutil.rmtree(path+"\\PAGES")
if os.path.exists(path+"\\WHOLEBOOK"):
    if len(os.listdir(path+"\\WHOLEBOOK") ) == 0:
        shutil.rmtree(path+"\\WHOLEBOOK")
if os.path.exists(path):
    if len(os.listdir(path)) == 0:
        shutil.rmtree(path)
        
# CREATE CHAPTERS FOLDER
os.makedirs(filelocation+"\\SCAN\\CHAPTERS")
os.makedirs(filelocation+"\\SCAN\\PAGES")
os.makedirs(filelocation+"\\SCAN\\WHOLEBOOK")

In [82]:
#check for scanned pdfs to 101 & 102
path = filelocation+"\\SCANNED FILES\\"+bookname+"\\"
dir_list = os.listdir(path)

if len(dir_list) == 2:
    for x in dir_list:
        if "101.pdf" in x:
            print("PDF file named 101 is available")
        elif "102.pdf" in x:
            print("PDF file named 102 is available")
        else: 
            print("ERROR: PDF files are missing")

PDF file named 101 is available
PDF file named 102 is available

In [83]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(df_bk1)

        CONTENTS THE LAST FIGHTING TOMMY Page From Page To No of Pages  \
0    FRONT COVER                     1-2         1       2           2
1   INTRODUCTION                    1-30         1      30          30
2      CHAPTER 1                      15        15      40          26
3      CHAPTER 2                      41        41      54          14
4      CHAPTER 3                      55        55      67          13
5      CHAPTER 4                      68        68      84          17
6      CHAPTER 5                      85        85     107          23
7      CHAPTER 6             108-126, 16       108     126          35
8      CHAPTER 7                     127       127     136          10
9      CHAPTER 8                     137       137     161          25
10     CHAPTER 9                     162       162     187          26
11    CHAPTER 10                     188       188     198          11
12    CHAPTER 11                 199-207       199     207           9
13           END                 208-240       208     240          33
14    BACK COVER                     1-2         1       2           2

    NonNumberedPages Total Pages  Split From  Split To
0                NaN           2           1         2
1                0.0          32           3        32
2                0.0          58          33        58
3                0.0          72          59        72
4                0.0          85          73        85
5                0.0         102          86       102
6                0.0         125         103       125
7               16.0         160         126       160
8                0.0         170         161       170
9                0.0         195         171       195
10               0.0         221         196       221
11               0.0         232         222       232
12               0.0         241         233       241
13               0.0         274         242       274
14               NaN         276         275       276

In [84]:
df_bk1

,CONTENTS,THE LAST FIGHTING TOMMY,Page From,Page To,No of Pages,NonNumberedPages,Total Pages,Split From,Split To
0,FRONT COVER,1-2,1,2,2,NaN,2,1,2
1,INTRODUCTION,1-30,1,30,30,0.0,32,3,32
2,CHAPTER 1,15,15,40,26,0.0,58,33,58
3,CHAPTER 2,41,41,54,14,0.0,72,59,72
4,CHAPTER 3,55,55,67,13,0.0,85,73,85
5,CHAPTER 4,68,68,84,17,0.0,102,86,102
6,CHAPTER 5,85,85,107,23,0.0,125,103,125
7,CHAPTER 6,"108-126, 16",108,126,35,16.0,160,126,160
8,CHAPTER 7,127,127,136,10,0.0,170,161,170
9,CHAPTER 8,137,137,161,25,0.0,195,171,195
10,CHAPTER 9,162,162,187,26,0.0,221,196,221
11,CHAPTER 10,188,188,198,11,0.0,232,222,232
12,CHAPTER 11,199-207,199,207,9,0.0,241,233,241
13,END,208-240,208,240,33,0.0,274,242,274
14,BACK COVER,1-2,1,2,2,NaN,276,275,276

In [85]:
# split wholebook to chapterwise 
from PyPDF2 import PdfFileWriter, PdfFileReader

path = filelocation+"\\SCANNED FILES\\"+bookname+"\\"
f = "102.pdf"

with open(path+f, "rb") as in_file:
    inputpdf = PdfFileReader(in_file)
    for x in range(len(df_bk1['CONTENTS'])):
        y = int(df_bk1['Split From'][x])
        z = int(df_bk1['Split To'][x])
        pdfname = str(x+101)+".pdf"
        print(pdfname)
        pages = []
        for j in range(y-1,z):
            pages.append(j)
        output = PdfFileWriter()
        for i in pages:
            output.addPage(inputpdf.getPage(i))
        with open(filelocation+"\\SCAN\\CHAPTERS\\"+pdfname, "wb") as outputStream:
            output.write(outputStream)
            outputStream.close()
        print(pages)
totalpages = inputpdf.numPages
print("Total No of Pages in Wholebook named "+str(f)+": "+str(totalpages))
in_file.close()

101.pdf
[0, 1]
102.pdf
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
103.pdf
[32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57]
104.pdf
[58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71]
105.pdf
[72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84]
106.pdf
[85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101]
107.pdf
[102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124]
108.pdf
[125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159]
109.pdf
[160, 161, 162, 163, 164, 165, 166, 167, 168, 169]
110.pdf
[170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194]
111.pdf
[195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220]
112.pdf
[221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231]
113.pdf
[232, 233, 234, 235, 236, 237, 238, 239, 240]
114.pdf
[241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273]
115.pdf
[274, 275]
Total No of Pages in Wholebook named 102.pdf: 276

In [86]:
# check indexing for wholebook named 101.pdf
from PyPDF2 import PdfFileWriter, PdfFileReader

path = filelocation+"\\SCANNED FILES\\"+bookname+"\\"
f = "101.pdf"

with open(path+f, "rb") as in_file:
    inputpdf = PdfFileReader(in_file)
    output = PdfFileWriter()
    for i in df_bk1['Split From']:
        page_no = int(i)-1
        output.addPage(inputpdf.getPage(page_no))
    with open(filelocation+"\\SCAN\\indexcheck_"+f, "wb") as outputStream:
        output.write(outputStream)
        outputStream.close()
in_file.close()

import subprocess
subprocess.Popen([filelocation+"\\SCAN\\indexcheck_"+f], shell=True)
#os.system(filelocation+"\\SCAN\\indexcheck_"+f)

In [87]:
# check indexing for wholebook named 102.pdf
from PyPDF2 import PdfFileWriter, PdfFileReader

path = filelocation+"\\SCANNED FILES\\"+bookname+"\\"
f = "102.pdf"

with open(path+f, "rb") as in_file:
    inputpdf = PdfFileReader(in_file)
    output = PdfFileWriter()
    for i in df_bk1['Split From']:
        page_no = int(i)-1
        output.addPage(inputpdf.getPage(page_no))
    with open(filelocation+"\\SCAN\\indexcheck_"+f, "wb") as outputStream:
        output.write(outputStream)
        outputStream.close()
in_file.close()

import subprocess
subprocess.Popen([filelocation+"\\SCAN\\indexcheck_"+f], shell=True)
#os.system(filelocation+"\\SCAN\\indexcheck_"+f)

In [88]:
df_bk2 = df_bk.copy()
df_bk2

,CONTENTS,THE LAST FIGHTING TOMMY,Page From,Page To,NonNumberedPages,No of Pages
0,COVER_FRONT OUTER,0,0,0,0,1
1,COVER_FRONT INNER,0,0,0,0,1
2,INTRODUCTION,1-30,1,30,0,30
3,CHAPTER 1,15,15,40,0,26
4,CHAPTER 2,41,41,54,0,14
5,CHAPTER 3,55,55,67,0,13
6,CHAPTER 4,68,68,84,0,17
7,CHAPTER 5,85,85,107,0,23
8,CHAPTER 6,"108-126, 16",108,126,16,35
9,CHAPTER 7,127,127,136,0,10
10,CHAPTER 8,137,137,161,0,25
11,CHAPTER 9,162,162,187,0,26
12,CHAPTER 10,188,188,198,0,11
13,CHAPTER 11,199-207,199,207,0,9
14,END,208-240,208,240,0,33
15,COVER_BACK INNER,0,0,0,0,1
16,COVER_BACK OUTER,0,0,0,0,1

In [89]:
# Add Total Pages, Split From & Split To
NoP=df_bk2['No of Pages']
NoP
TOTALPAGES = [NoP[0]]
j = int(NoP[0])
for i in range(1,len(NoP)):
    if df_bk2['Page From'][i] == 0 and df_bk2['Page To'][i-1] == 0:
        j = j + int(NoP[i])
        TOTALPAGES.append(j)        
    elif df_bk2['Page From'][i] == df_bk2['Page To'][i-1]:
        j = j + int(NoP[i])-1
        TOTALPAGES.append(j)
    else:
        j = j + int(NoP[i])
        TOTALPAGES.append(j)
df_bk2['Total Pages'] = TOTALPAGES
        
splitfrom=[int(1)]
splitto=[int(1)]

for i in range(1,len(df_bk2['CONTENTS'])):
    if df_bk2['Page From'][i] == 0 and df_bk2['Page To'][i-1] == 0:
        p = df_bk2['Total Pages'][i-1]+1
    elif df_bk2['Page From'][i] == df_bk2['Page To'][i-1]:
        p = df_bk2['Total Pages'][i-1]
    else:
        p = int(df_bk2['Total Pages'][i-1])+1
    splitfrom.append(p)
    q = p + int(df_bk2['No of Pages'][i]) - 1
    splitto.append(q)

df_bk2['Split From']=splitfrom
df_bk2['Split To']=splitto

df_bk2

,CONTENTS,THE LAST FIGHTING TOMMY,Page From,Page To,NonNumberedPages,No of Pages,Total Pages,Split From,Split To
0,COVER_FRONT OUTER,0,0,0,0,1,1,1,1
1,COVER_FRONT INNER,0,0,0,0,1,2,2,2
2,INTRODUCTION,1-30,1,30,0,30,32,3,32
3,CHAPTER 1,15,15,40,0,26,58,33,58
4,CHAPTER 2,41,41,54,0,14,72,59,72
5,CHAPTER 3,55,55,67,0,13,85,73,85
6,CHAPTER 4,68,68,84,0,17,102,86,102
7,CHAPTER 5,85,85,107,0,23,125,103,125
8,CHAPTER 6,"108-126, 16",108,126,16,35,160,126,160
9,CHAPTER 7,127,127,136,0,10,170,161,170
10,CHAPTER 8,137,137,161,0,25,195,171,195
11,CHAPTER 9,162,162,187,0,26,221,196,221
12,CHAPTER 10,188,188,198,0,11,232,222,232
13,CHAPTER 11,199-207,199,207,0,9,241,233,241
14,END,208-240,208,240,0,33,274,242,274
15,COVER_BACK INNER,0,0,0,0,1,275,275,275
16,COVER_BACK OUTER,0,0,0,0,1,276,276,276

In [90]:
# Create Filename for Separate Pages
z = vendorcode+"_"+bookname+"_SEPARATE_"
filename=[]
for i in range(len(df_bk2['CONTENTS'])):
    if df_bk2['Page From'][i] == 0:
        r = z+df_bk2['CONTENTS'][i]
        filename.append(r)
    elif df_bk2['Page From'][i] > 0:
        p = int(df_bk2['No of Pages'][i])
        for j in range(1,p+1):
            r = z + df_bk2['CONTENTS'][i] + "_" + str(j)
            filename.append(r)
print(len(filename))
filename

276

['TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_COVER_FRONT OUTER',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_COVER_FRONT INNER',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_11',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_12',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_13',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_14',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_15',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_16',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_17',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_18',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_19',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_20',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_21',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_22',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_23',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_24',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_25',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_26',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_27',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_28',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_29',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_INTRODUCTION_30',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_11',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_12',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_13',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_14',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_15',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_16',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_17',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_18',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_19',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_20',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_21',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_22',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_23',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_24',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_25',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 1_26',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_11',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_12',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_13',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 2_14',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_11',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_12',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 3_13',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_11',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_12',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_13',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_14',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_15',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_16',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 4_17',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_11',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_12',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_13',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_14',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_15',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_16',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_17',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_18',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_19',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_20',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_21',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_22',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 5_23',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_11',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_12',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_13',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_14',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_15',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_16',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_17',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_18',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_19',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_20',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_21',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_22',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_23',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_24',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_25',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_26',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_27',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_28',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_29',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_30',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_31',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_32',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_33',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_34',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 6_35',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 7_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 7_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 7_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 7_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 7_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 7_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 7_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 7_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 7_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 7_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_11',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_12',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_13',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_14',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_15',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_16',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_17',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_18',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_19',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_20',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_21',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_22',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_23',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_24',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 8_25',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_11',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_12',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_13',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_14',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_15',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_16',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_17',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_18',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_19',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_20',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_21',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_22',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_23',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_24',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_25',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 9_26',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 10_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 10_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 10_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 10_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 10_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 10_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 10_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 10_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 10_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 10_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 10_11',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 11_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 11_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 11_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 11_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 11_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 11_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 11_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 11_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_CHAPTER 11_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_1',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_2',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_3',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_4',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_5',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_6',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_7',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_8',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_9',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_10',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_11',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_12',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_13',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_14',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_15',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_16',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_17',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_18',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_19',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_20',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_21',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_22',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_23',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_24',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_25',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_26',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_27',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_28',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_29',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_30',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_31',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_32',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_END_33',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_COVER_BACK INNER',
 'TSS_TN_744090_THE LAST FIGHTING TOMMY_SEPARATE_COVER_BACK OUTER']

In [91]:
# split wholebook1 to pagewise 
from PyPDF2 import PdfFileWriter, PdfFileReader

path = filelocation+"\\SCANNED FILES\\"+bookname+"\\"
f = "101.pdf"
i = 0
with open(path+f, "rb") as in_file:
    inputpdf = PdfFileReader(in_file)
    for x in range(len(df_bk2['CONTENTS'])):
        y = int(df_bk2['Split From'][x])
        z = int(df_bk2['Split To'][x])
        for j in range(y-1,z):
            pdfname = str(i+101)+".pdf"
            print(pdfname)
            print (j)
            output = PdfFileWriter()
            output.addPage(inputpdf.getPage(j))
            with open(filelocation+"\\SCAN\\PAGES\\"+pdfname, "wb") as outputStream:
                output.write(outputStream)
                outputStream.close()
                i = i + 1
totalpages = inputpdf.numPages
print("Total No of Pages in Wholebook named "+str(f)+": "+str(totalpages))
in_file.close()

101.pdf
0
102.pdf
1
103.pdf
2
104.pdf
3
105.pdf
4
106.pdf
5
107.pdf
6
108.pdf
7
109.pdf
8
110.pdf
9
111.pdf
10
112.pdf
11
113.pdf
12
114.pdf
13
115.pdf
14
116.pdf
15
117.pdf
16
118.pdf
17
119.pdf
18
120.pdf
19
121.pdf
20
122.pdf
21
123.pdf
22
124.pdf
23
125.pdf
24
126.pdf
25
127.pdf
26
128.pdf
27
129.pdf
28
130.pdf
29
131.pdf
30
132.pdf
31
133.pdf
32
134.pdf
33
135.pdf
34
136.pdf
35
137.pdf
36
138.pdf
37
139.pdf
38
140.pdf
39
141.pdf
40
142.pdf
41
143.pdf
42
144.pdf
43
145.pdf
44
146.pdf
45
147.pdf
46
148.pdf
47
149.pdf
48
150.pdf
49
151.pdf
50
152.pdf
51
153.pdf
52
154.pdf
53
155.pdf
54
156.pdf
55
157.pdf
56
158.pdf
57
159.pdf
58
160.pdf
59
161.pdf
60
162.pdf
61
163.pdf
62
164.pdf
63
165.pdf
64
166.pdf
65
167.pdf
66
168.pdf
67
169.pdf
68
170.pdf
69
171.pdf
70
172.pdf
71
173.pdf
72
174.pdf
73
175.pdf
74
176.pdf
75
177.pdf
76
178.pdf
77
179.pdf
78
180.pdf
79
181.pdf
80
182.pdf
81
183.pdf
82
184.pdf
83
185.pdf
84
186.pdf
85
187.pdf
86
188.pdf
87
189.pdf
88
190.pdf
89
191.pdf
90
192.pdf
91
193.pdf
92
194.pdf
93
195.pdf
94
196.pdf
95
197.pdf
96
198.pdf
97
199.pdf
98
200.pdf
99
201.pdf
100
202.pdf
101
203.pdf
102
204.pdf
103
205.pdf
104
206.pdf
105
207.pdf
106
208.pdf
107
209.pdf
108
210.pdf
109
211.pdf
110
212.pdf
111
213.pdf
112
214.pdf
113
215.pdf
114
216.pdf
115
217.pdf
116
218.pdf
117
219.pdf
118
220.pdf
119
221.pdf
120
222.pdf
121
223.pdf
122
224.pdf
123
225.pdf
124
226.pdf
125
227.pdf
126
228.pdf
127
229.pdf
128
230.pdf
129
231.pdf
130
232.pdf
131
233.pdf
132
234.pdf
133
235.pdf
134
236.pdf
135
237.pdf
136
238.pdf
137
239.pdf
138
240.pdf
139
241.pdf
140
242.pdf
141
243.pdf
142
244.pdf
143
245.pdf
144
246.pdf
145
247.pdf
146
248.pdf
147
249.pdf
148
250.pdf
149
251.pdf
150
252.pdf
151
253.pdf
152
254.pdf
153
255.pdf
154
256.pdf
155
257.pdf
156
258.pdf
157
259.pdf
158
260.pdf
159
261.pdf
160
262.pdf
161
263.pdf
162
264.pdf
163
265.pdf
164
266.pdf
165
267.pdf
166
268.pdf
167
269.pdf
168
270.pdf
169
271.pdf
170
272.pdf
171
273.pdf
172
274.pdf
173
275.pdf
174
276.pdf
175
277.pdf
176
278.pdf
177
279.pdf
178
280.pdf
179
281.pdf
180
282.pdf
181
283.pdf
182
284.pdf
183
285.pdf
184
286.pdf
185
287.pdf
186
288.pdf
187
289.pdf
188
290.pdf
189
291.pdf
190
292.pdf
191
293.pdf
192
294.pdf
193
295.pdf
194
296.pdf
195
297.pdf
196
298.pdf
197
299.pdf
198
300.pdf
199
301.pdf
200
302.pdf
201
303.pdf
202
304.pdf
203
305.pdf
204
306.pdf
205
307.pdf
206
308.pdf
207
309.pdf
208
310.pdf
209
311.pdf
210
312.pdf
211
313.pdf
212
314.pdf
213
315.pdf
214
316.pdf
215
317.pdf
216
318.pdf
217
319.pdf
218
320.pdf
219
321.pdf
220
322.pdf
221
323.pdf
222
324.pdf
223
325.pdf
224
326.pdf
225
327.pdf
226
328.pdf
227
329.pdf
228
330.pdf
229
331.pdf
230
332.pdf
231
333.pdf
232
334.pdf
233
335.pdf
234
336.pdf
235
337.pdf
236
338.pdf
237
339.pdf
238
340.pdf
239
341.pdf
240
342.pdf
241
343.pdf
242
344.pdf
243
345.pdf
244
346.pdf
245
347.pdf
246
348.pdf
247
349.pdf
248
350.pdf
249
351.pdf
250
352.pdf
251
353.pdf
252
354.pdf
253
355.pdf
254
356.pdf
255
357.pdf
256
358.pdf
257
359.pdf
258
360.pdf
259
361.pdf
260
362.pdf
261
363.pdf
262
364.pdf
263
365.pdf
264
366.pdf
265
367.pdf
266
368.pdf
267
369.pdf
268
370.pdf
269
371.pdf
270
372.pdf
271
373.pdf
272
374.pdf
273
375.pdf
274
376.pdf
275
Total No of Pages in Wholebook named 101.pdf: 276

In [92]:
#check list of separate pdf and filenames created
print(len(filename))

path = filelocation+"\\SCAN\\PAGES\\"
dir_list = os.listdir(path)
print(len(dir_list))
#print(dfxl[bookname][2]+dfxl[bookname][3]*2+dfxl[bookname][4]*2)
#if len(filename) == int(dfxl[bookname][2]+(dfxl[bookname][3]*2)+(dfxl[bookname][4]*2)):

if len(filename) == len(dir_list):
    print("Total numbers of separate filenames matches with total no of pages")
else:
    print("Error", "THERE IS A MISMATCH BETWEEN TOTAL NO OF PAGES WITH NO OF SEPARATE PAGES CREATED IN PYTHON")
    sys.exit()

276
276
Total numbers of separate filenames matches with total no of pages

path = filelocation+"\\SCAN\\PAGES"
dir_list = os.listdir(path)

dir_list.sort()
dir_list

In [93]:
# check total pages in each chapters
from PyPDF2 import PdfFileWriter, PdfFileReader

path = filelocation+"\\SCAN\\CHAPTERS\\"
dir_list = os.listdir(path)
i = 0

for f in dir_list:
    with open(path+f, "rb") as in_file:
        inputpdf = PdfFileReader(in_file)
        totalpages = inputpdf.numPages
        i = i + totalpages
    print("Total No of Pages in "+f+": "+str(totalpages)+"; cummulative total: "+str(i))
in_file.close()

if len(filename) == i:
    print("No. of Pages matches with individual no. of pages: "+str(i))
else:
    print("THERE IS A MISMATCH IN NO OF PAGES")
    sys.exit()

Total No of Pages in 101.pdf: 2; cummulative total: 2
Total No of Pages in 102.pdf: 30; cummulative total: 32
Total No of Pages in 103.pdf: 26; cummulative total: 58
Total No of Pages in 104.pdf: 14; cummulative total: 72
Total No of Pages in 105.pdf: 13; cummulative total: 85
Total No of Pages in 106.pdf: 17; cummulative total: 102
Total No of Pages in 107.pdf: 23; cummulative total: 125
Total No of Pages in 108.pdf: 35; cummulative total: 160
Total No of Pages in 109.pdf: 10; cummulative total: 170
Total No of Pages in 110.pdf: 25; cummulative total: 195
Total No of Pages in 111.pdf: 26; cummulative total: 221
Total No of Pages in 112.pdf: 11; cummulative total: 232
Total No of Pages in 113.pdf: 9; cummulative total: 241
Total No of Pages in 114.pdf: 33; cummulative total: 274
Total No of Pages in 115.pdf: 2; cummulative total: 276
No. of Pages matches with individual no. of pages: 276

In [94]:
#rename individual pages
path = filelocation+"\\SCAN\\PAGES\\"
dir_list = os.listdir(path)

print (len(dir_list))
print (len(filename))

if len(dir_list)==len(filename):
    for i in range(len(dir_list)):
        for x in os.listdir(path):
            if dir_list[i] == x:
                y = filename[i]+".pdf"
                source = path + x
                dest = path + y
                os.rename(source,dest)
else:
    print("list of files in the path: "+str(len(dir_list)))
    print("No of filenames to be renamed: "+str(len(filename)))
    print ("Mismatch in No of pages ")

276
276

In [95]:
# rename chapters
path = filelocation+"\\SCAN\\CHAPTERS\\"
dir_list = os.listdir(path)

print (len(dir_list))
print (len(df_bk1['CONTENTS']))


i = 0
if len(dir_list) == len(df_bk1['CONTENTS']):
    for x in dir_list:
        if df_bk1['Page From'].iloc[i] == 0:
            j = vendorcode+"_"+bookname+"_PAGES_"+str(df_bk1['CONTENTS'].iloc[i])+".pdf"
            source = path + x
            dest = path + j
            os.rename(source,dest)
            i = i + 1
        elif "FRONT" in df_bk1['CONTENTS'].iloc[i]:
            j = vendorcode+"_"+bookname+"_PAGES_COVER_"+str(df_bk1['CONTENTS'].iloc[i])+".pdf"
            source = path + x
            dest = path + j
            os.rename(source,dest)
            i = i + 1
        elif "BACK" in df_bk1['CONTENTS'].iloc[i]:
            j = vendorcode+"_"+bookname+"_PAGES_COVER_"+str(df_bk1['CONTENTS'].iloc[i])+".pdf"
            source = path + x
            dest = path + j
            os.rename(source,dest)
            i = i + 1
        else:
            p = df_bk1['Page From'].iloc[i]
            q = df_bk1['Page To'].iloc[i]
            j = vendorcode+"_"+bookname+"_PAGES_"+str(df_bk1['CONTENTS'].iloc[i])+"_"+str(p)+"-"+str(q)+".pdf"
            source = path + x
            dest = path + j
            os.rename(source,dest)
            i = i + 1

15
15

In [96]:
# copy and rename wholebook

#copy wholebook
f = "101.pdf"
source_dir = filelocation+"\\SCANNED FILES\\"+bookname+"\\"+f
destination_dir = filelocation+"\\SCAN\\WHOLEBOOK\\"+f
shutil.copyfile(source_dir,destination_dir)


#rename wholebook
path = filelocation+"\\SCAN\\WHOLEBOOK\\"
dir_list = os.listdir(path)

if len(dir_list) == 1:
    for x in dir_list:
        j = vendorcode+"_"+bookname+"_WHOLEBOOK.pdf"
        source = path + x
        dest = path + j
        os.rename(source,dest)

In [97]:
#move book parts
import shutil

j = vendorcode+"_"+bookname
k = vendorcode+"_"+bookname+"_"

file_source = filelocation+"\\SCAN\\CHAPTERS\\"
get_files = os.listdir(filelocation+"\\SCAN\\CHAPTERS\\")

#move wholebook file
os.makedirs(filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"WHOLEBOOK")
file_source1 = filelocation+"\\SCAN\\WHOLEBOOK\\"
file_destination = filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"WHOLEBOOK"
sel_files = (f for f in os.listdir(filelocation+"\\SCAN\\WHOLEBOOK\\") if "WHOLEBOOK" in f)
for g in sel_files:
    shutil.move(str(file_source1 + g), str(file_destination))
    
    
#move book pages
os.makedirs(filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"PAGES\\"+k+"PAGES_COVER")
for i in range(len(df_bk1['CONTENTS'])):
    file_list=os.listdir(filelocation+"\\SCAN\\CHAPTERS\\")
    #print(df_bk1['CONTENTS'].iloc[i])
    if "FRONT" in df_bk1['CONTENTS'].iloc[i]:
        file_destination = filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"PAGES\\"+k+"PAGES_COVER"
        z = "FRONT"
        sel_files = (f for f in file_list if z in f)
        for g in sel_files:
            shutil.move(str(file_source + g), str("\\\\?\\" +file_destination))
    elif "BACK" in df_bk1['CONTENTS'].iloc[i]:
        file_destination = filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"PAGES\\"+k+"PAGES_COVER"
        z = "BACK"
        sel_files = (f for f in file_list if z in f)
        for g in sel_files:
            shutil.move(str(file_source + g), str("\\\\?\\" +file_destination))
    else:
        os.makedirs(filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"PAGES\\"+k+"PAGES_"+df_bk1['CONTENTS'].iloc[i])
        file_destination = filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"PAGES\\"+k+"PAGES_"+df_bk1['CONTENTS'].iloc[i]
        z = df_bk1['CONTENTS'].iloc[i]+"_"
        sel_files = (f for f in file_list if z in f)
        for g in sel_files:
            shutil.move(str(file_source + g), str("\\\\?\\" +file_destination))

In [98]:
# move individual pages
import shutil

j = vendorcode+"_"+bookname
k = vendorcode+"_"+bookname+"_"

import win32api
import ntpath

file_source = win32api.GetShortPathName(filelocation+"\\SCAN\\PAGES\\")
get_files = os.listdir(filelocation+"\\SCAN\\PAGES\\")

#move separate pages
os.makedirs(filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"SEPARATE\\"+k+"SEPARATE_COVER")
for i in range(len(df_bk1['CONTENTS'])):
    file_list=os.listdir(filelocation+"\\SCAN\\PAGES\\")
    #print(df_bk1['CONTENTS'].iloc[i])
    if "FRONT" in df_bk1['CONTENTS'].iloc[i]:
        file_destination = filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"SEPARATE\\"+k+"SEPARATE_COVER"
        z = "FRONT"
        sel_files = (f for f in file_list if z in f)
        for g in sel_files:
            shutil.move(win32api.GetShortPathName(file_source + g), ("\\\\?\\" +file_destination))
    elif "BACK" in df_bk1['CONTENTS'].iloc[i]:
        file_destination = filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"SEPARATE\\"+k+"SEPARATE_COVER"
        z = "BACK"
        sel_files = (f for f in file_list if z in f)
        for g in sel_files:
            shutil.move(win32api.GetShortPathName(file_source + g), ("\\\\?\\" +file_destination))
    else:
        os.makedirs(filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"SEPARATE\\"+k+"SEPARATE_"+df_bk1['CONTENTS'].iloc[i])
        file_destination = filelocation+"\\"+vendorcode+"\\"+j+"\\"+k+"SEPARATE\\"+k+"SEPARATE_"+df_bk1['CONTENTS'].iloc[i]
        z = df_bk1['CONTENTS'].iloc[i]+"_"
        sel_files = (f for f in file_list if z in f)
        for g in sel_files:
            shutil.move(win32api.GetShortPathName(file_source + g), ("\\\\?\\" +file_destination))

In [99]:
# create notepad file:
df_notes=dfxl[['CONTENTS', bookname]].copy()
#df_notes = df_notes.dropna(subset=[bookname], inplace=True)
df_notes
if df_notes[bookname][0] != 0:
    path = filelocation+"\\"+vendorcode+"\\"+vendorcode+"_"+bookname+"\\"
    j = vendorcode+"_"+bookname+"_NOTES"
    with open(path+j+'.txt', 'w') as f:
        f.write(str(df_notes[bookname][0]))
        f.close

In [100]:
# if scan folder is empty or not:
if len(os.listdir(filelocation+"\\SCAN\\CHAPTERS") ) == 0:
    print(filelocation+"\SCAN\CHAPTERS IS EMPTY")
else:    
    print("ERROR!!!!!......."+filelocation+"\SCAN\CHAPTERS is not empty")

if len(os.listdir(filelocation+"\\SCAN\\PAGES") ) == 0:
    print(filelocation+"\SCAN\PAGES IS EMPTY")
else:    
    print("ERROR!!!!!......."+filelocation+"\SCAN\PAGES is not empty")

if len(os.listdir(filelocation+"\\SCAN\\WHOLEBOOK") ) == 0:
    print(filelocation+"\SCAN\WHOLEBOOK IS EMPTY")
else:    
    print("ERROR!!!!!......."+filelocation+"\SCAN\WHOLEBOOK is not empty")

E:\B1\SCAN\CHAPTERS IS EMPTY
E:\B1\SCAN\PAGES IS EMPTY
E:\B1\SCAN\WHOLEBOOK IS EMPTY

In [101]:
# to find empty folders in the filelocation:
import os
  
empty = []
  
# Traversing through path
path = filelocation + "\\" + vendorcode
for root, dirs, files in os.walk(path):
  
    # Checking the size of tuple
    if not len(dirs) and not len(files):
  
        # Adding the empty directory to
        # list
        empty.append(root)
        
print("Empty Directories:")
print(empty)

Empty Directories:
[]